In [53]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [54]:
## Load  the dataset 
data = pd.read_csv("../data/Modular_coding.csv")

In [55]:
data.head(3)

,Unnamed: 0,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,Target
0,0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,999,0,unknown,0
1,1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,999,0,unknown,0
2,2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,999,0,unknown,0

In [56]:
data = data.drop(columns=['Unnamed: 0'])

In [57]:
data.head(2)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,Target
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,999,0,unknown,0
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,999,0,unknown,0

In [58]:
label_encoder_default = LabelEncoder()
data['default']  = label_encoder_default.fit_transform(data['default'])
data

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,Target
0,58,management,married,tertiary,0,2143,yes,no,unknown,5,may,261,1,999,0,unknown,0
1,44,technician,single,secondary,0,29,yes,no,unknown,5,may,151,1,999,0,unknown,0
2,33,entrepreneur,married,secondary,0,2,yes,yes,unknown,5,may,76,1,999,0,unknown,0
3,47,blue-collar,married,unknown,0,1506,yes,no,unknown,5,may,92,1,999,0,unknown,0
4,33,unknown,single,unknown,0,1,no,no,unknown,5,may,198,1,999,0,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,0,825,no,no,cellular,17,nov,977,3,999,0,unknown,1
45207,71,retired,divorced,primary,0,1729,no,no,cellular,17,nov,456,2,999,0,unknown,1
45208,72,retired,married,secondary,0,5715,no,no,cellular,17,nov,1127,5,184,3,success,1
45209,57,blue-collar,married,secondary,0,668,no,no,telephone,17,nov,508,4,999,0,unknown,0
45210,37,entrepreneur,married,secondary,0,2971,no,no,cellular,17,nov,361,2,188,11,other,0

In [59]:
label_encoder_loan = LabelEncoder()
data['loan']  = label_encoder_default.fit_transform(data['loan'])
data

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,Target
0,58,management,married,tertiary,0,2143,yes,0,unknown,5,may,261,1,999,0,unknown,0
1,44,technician,single,secondary,0,29,yes,0,unknown,5,may,151,1,999,0,unknown,0
2,33,entrepreneur,married,secondary,0,2,yes,1,unknown,5,may,76,1,999,0,unknown,0
3,47,blue-collar,married,unknown,0,1506,yes,0,unknown,5,may,92,1,999,0,unknown,0
4,33,unknown,single,unknown,0,1,no,0,unknown,5,may,198,1,999,0,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,0,825,no,0,cellular,17,nov,977,3,999,0,unknown,1
45207,71,retired,divorced,primary,0,1729,no,0,cellular,17,nov,456,2,999,0,unknown,1
45208,72,retired,married,secondary,0,5715,no,0,cellular,17,nov,1127,5,184,3,success,1
45209,57,blue-collar,married,secondary,0,668,no,0,telephone,17,nov,508,4,999,0,unknown,0
45210,37,entrepreneur,married,secondary,0,2971,no,0,cellular,17,nov,361,2,188,11,other,0

In [60]:
label_encoder_housing = LabelEncoder()
data['housing']  = label_encoder_default.fit_transform(data['housing'])
data

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,Target
0,58,management,married,tertiary,0,2143,1,0,unknown,5,may,261,1,999,0,unknown,0
1,44,technician,single,secondary,0,29,1,0,unknown,5,may,151,1,999,0,unknown,0
2,33,entrepreneur,married,secondary,0,2,1,1,unknown,5,may,76,1,999,0,unknown,0
3,47,blue-collar,married,unknown,0,1506,1,0,unknown,5,may,92,1,999,0,unknown,0
4,33,unknown,single,unknown,0,1,0,0,unknown,5,may,198,1,999,0,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,0,825,0,0,cellular,17,nov,977,3,999,0,unknown,1
45207,71,retired,divorced,primary,0,1729,0,0,cellular,17,nov,456,2,999,0,unknown,1
45208,72,retired,married,secondary,0,5715,0,0,cellular,17,nov,1127,5,184,3,success,1
45209,57,blue-collar,married,secondary,0,668,0,0,telephone,17,nov,508,4,999,0,unknown,0
45210,37,entrepreneur,married,secondary,0,2971,0,0,cellular,17,nov,361,2,188,11,other,0

In [61]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder_job = OneHotEncoder()
job_one_hot_encoder = one_hot_encoder_job.fit_transform(data[['job']]).toarray()
job_one_hot_encoder

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], shape=(45211, 12))

In [62]:
one_hot_encoder_job.get_feature_names_out(['job'])

array(['job_admin.', 'job_blue-collar', 'job_entrepreneur',
       'job_housemaid', 'job_management', 'job_retired',
       'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'job_unknown'], dtype=object)

In [63]:
job_encoded_df = pd.DataFrame(job_one_hot_encoder, columns=one_hot_encoder_job.get_feature_names_out(['job']))
job_encoded_df

,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
45206,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
45207,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
45208,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
45209,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45210,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [64]:
data = pd.concat([data.drop('job', axis=1),job_encoded_df], axis=1)

In [65]:
data.head()

,age,marital,education,default,balance,housing,loan,contact,day,month,...,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown
0,58,married,tertiary,0,2143,1,0,unknown,5,may,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,44,single,secondary,0,29,1,0,unknown,5,may,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,33,married,secondary,0,2,1,1,unknown,5,may,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,47,married,unknown,0,1506,1,0,unknown,5,may,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,33,single,unknown,0,1,0,0,unknown,5,may,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [66]:

month_mapping = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "nov": 11,
    "dec": 12
}

data["month"] = data["month"].str.lower().map(month_mapping)

print(data["month"].head())

0    5
1    5
2    5
3    5
4    5
Name: month, dtype: int64

In [67]:
data.head(3)

,age,marital,education,default,balance,housing,loan,contact,day,month,...,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown
0,58,married,tertiary,0,2143,1,0,unknown,5,5,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,44,single,secondary,0,29,1,0,unknown,5,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,33,married,secondary,0,2,1,1,unknown,5,5,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [68]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder_education = OneHotEncoder()
education_one_hot_encoder = one_hot_encoder_education.fit_transform(data[['education']]).toarray()
education_one_hot_encoder

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       ...,
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]], shape=(45211, 4))

In [69]:
one_hot_encoder_education.get_feature_names_out(['education'])

array(['education_primary', 'education_secondary', 'education_tertiary',
       'education_unknown'], dtype=object)

In [70]:
education_encoded_df = pd.DataFrame(education_one_hot_encoder, columns=one_hot_encoder_education.get_feature_names_out(['education']))
education_encoded_df

,education_primary,education_secondary,education_tertiary,education_unknown
0,0.0,0.0,1.0,0.0
1,0.0,1.0,0.0,0.0
2,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,1.0
...,...,...,...,...
45206,0.0,0.0,1.0,0.0
45207,1.0,0.0,0.0,0.0
45208,0.0,1.0,0.0,0.0
45209,0.0,1.0,0.0,0.0
45210,0.0,1.0,0.0,0.0

In [71]:
data = pd.concat([data.drop('education', axis=1),education_encoded_df], axis=1)

In [72]:
data

,age,marital,default,balance,housing,loan,contact,day,month,duration,...,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown,education_primary,education_secondary,education_tertiary,education_unknown
0,58,married,0,2143,1,0,unknown,5,5,261,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,44,single,0,29,1,0,unknown,5,5,151,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,33,married,0,2,1,1,unknown,5,5,76,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,47,married,0,1506,1,0,unknown,5,5,92,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,33,single,0,1,0,0,unknown,5,5,198,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,married,0,825,0,0,cellular,17,11,977,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
45207,71,divorced,0,1729,0,0,cellular,17,11,456,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
45208,72,married,0,5715,0,0,cellular,17,11,1127,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
45209,57,married,0,668,0,0,telephone,17,11,508,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
45210,37,married,0,2971,0,0,cellular,17,11,361,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [73]:
data

,age,marital,default,balance,housing,loan,contact,day,month,duration,...,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown,education_primary,education_secondary,education_tertiary,education_unknown
0,58,married,0,2143,1,0,unknown,5,5,261,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,44,single,0,29,1,0,unknown,5,5,151,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,33,married,0,2,1,1,unknown,5,5,76,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,47,married,0,1506,1,0,unknown,5,5,92,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,33,single,0,1,0,0,unknown,5,5,198,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,married,0,825,0,0,cellular,17,11,977,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
45207,71,divorced,0,1729,0,0,cellular,17,11,456,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
45208,72,married,0,5715,0,0,cellular,17,11,1127,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
45209,57,married,0,668,0,0,telephone,17,11,508,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
45210,37,married,0,2971,0,0,cellular,17,11,361,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [74]:

# One-hot encoding
data = pd.get_dummies(
    data,
    columns=["marital","contact"],
    dtype=int
)

print(data.head())

   age  default  balance  housing  loan  day  month  duration  campaign  \
0   58        0     2143        1     0    5      5       261         1
1   44        0       29        1     0    5      5       151         1
2   33        0        2        1     1    5      5        76         1
3   47        0     1506        1     0    5      5        92         1
4   33        0        1        0     0    5      5       198         1

   pdays  ...  education_primary education_secondary  education_tertiary  \
0    999  ...                0.0                 0.0                 1.0
1    999  ...                0.0                 1.0                 0.0
2    999  ...                0.0                 1.0                 0.0
3    999  ...                0.0                 0.0                 0.0
4    999  ...                0.0                 0.0                 0.0

   education_unknown  marital_divorced  marital_married  marital_single  \
0                0.0                 0                1               0
1                0.0                 0                0               1
2                0.0                 0                1               0
3                1.0                 0                1               0
4                1.0                 0                0               1

   contact_cellular  contact_telephone  contact_unknown
0                 0                  0                1
1                 0                  0                1
2                 0                  0                1
3                 0                  0                1
4                 0                  0                1

[5 rows x 35 columns]

In [75]:
data

,age,default,balance,housing,loan,day,month,duration,campaign,pdays,...,education_primary,education_secondary,education_tertiary,education_unknown,marital_divorced,marital_married,marital_single,contact_cellular,contact_telephone,contact_unknown
0,58,0,2143,1,0,5,5,261,1,999,...,0.0,0.0,1.0,0.0,0,1,0,0,0,1
1,44,0,29,1,0,5,5,151,1,999,...,0.0,1.0,0.0,0.0,0,0,1,0,0,1
2,33,0,2,1,1,5,5,76,1,999,...,0.0,1.0,0.0,0.0,0,1,0,0,0,1
3,47,0,1506,1,0,5,5,92,1,999,...,0.0,0.0,0.0,1.0,0,1,0,0,0,1
4,33,0,1,0,0,5,5,198,1,999,...,0.0,0.0,0.0,1.0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,0,825,0,0,17,11,977,3,999,...,0.0,0.0,1.0,0.0,0,1,0,1,0,0
45207,71,0,1729,0,0,17,11,456,2,999,...,1.0,0.0,0.0,0.0,1,0,0,1,0,0
45208,72,0,5715,0,0,17,11,1127,5,184,...,0.0,1.0,0.0,0.0,0,1,0,1,0,0
45209,57,0,668,0,0,17,11,508,4,999,...,0.0,1.0,0.0,0.0,0,1,0,0,1,0
45210,37,0,2971,0,0,17,11,361,2,188,...,0.0,1.0,0.0,0.0,0,1,0,1,0,0

In [76]:

# One-hot encoding
data = pd.get_dummies(
    data,
    columns=["poutcome"],
    dtype=int
)

print(data.head())

   age  default  balance  housing  loan  day  month  duration  campaign  \
0   58        0     2143        1     0    5      5       261         1
1   44        0       29        1     0    5      5       151         1
2   33        0        2        1     1    5      5        76         1
3   47        0     1506        1     0    5      5        92         1
4   33        0        1        0     0    5      5       198         1

   pdays  ...  marital_divorced  marital_married  marital_single  \
0    999  ...                 0                1               0
1    999  ...                 0                0               1
2    999  ...                 0                1               0
3    999  ...                 0                1               0
4    999  ...                 0                0               1

   contact_cellular  contact_telephone  contact_unknown  poutcome_failure  \
0                 0                  0                1                 0
1                 0                  0                1                 0
2                 0                  0                1                 0
3                 0                  0                1                 0
4                 0                  0                1                 0

   poutcome_other  poutcome_success  poutcome_unknown
0               0                 0                 1
1               0                 0                 1
2               0                 0                 1
3               0                 0                 1
4               0                 0                 1

[5 rows x 38 columns]

In [77]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 38 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  45211 non-null  int64
 1   default              45211 non-null  int64
 2   balance              45211 non-null  int64
 3   housing              45211 non-null  int64
 4   loan                 45211 non-null  int64
 5   day                  45211 non-null  int64
 6   month                45211 non-null  int64
 7   duration             45211 non-null  int64
 8   campaign             45211 non-null  int64
 9   pdays                45211 non-null  int64
 10  previous             45211 non-null  int64
 11  Target               45211 non-null  int64
 12  job_admin.           45211 non-null  float64
 13  job_blue-collar      45211 non-null  float64
 14  job_entrepreneur     45211 non-null  float64
 15  job_housemaid        45211 non-null  float64
 16  job_management       45211 non-null  float64
 17  job_retired          45211 non-null  float64
 18  job_self-employed    45211 non-null  float64
 19  job_services         45211 non-null  float64
 20  job_student          45211 non-null  float64
 21  job_technician       45211 non-null  float64
 22  job_unemployed       45211 non-null  float64
 23  job_unknown          45211 non-null  float64
 24  education_primary    45211 non-null  float64
 25  education_secondary  45211 non-null  float64
 26  education_tertiary   45211 non-null  float64
 27  education_unknown    45211 non-null  float64
 28  marital_divorced     45211 non-null  int64
 29  marital_married      45211 non-null  int64
 30  marital_single       45211 non-null  int64
 31  contact_cellular     45211 non-null  int64
 32  contact_telephone    45211 non-null  int64
 33  contact_unknown      45211 non-null  int64
 34  poutcome_failure     45211 non-null  int64
 35  poutcome_other       45211 non-null  int64
 36  poutcome_success     45211 non-null  int64
 37  poutcome_unknown     45211 non-null  int64
dtypes: float64(16), int64(22)
memory usage: 13.1 MB

In [78]:

for col in data.columns:
    print(f"\nColumn: {col}")
    print(data[col].unique())

Column: age
[58 44 33 47 35 28 42 43 41 29 53 57 51 45 60 56 32 25 40 39 52 46 36 49
 59 37 50 54 55 48 24 38 31 30 27 34 23 26 61 22 21 20 66 62 83 75 67 70
 65 68 64 69 72 71 19 76 85 63 90 82 73 74 78 80 94 79 77 86 95 81 18 89
 84 87 92 93 88]

Column: default
[0 1]

Column: balance
[ 2143    29     2 ...  8205 14204 16353]

Column: housing
[1 0]

Column: loan
[0 1]

Column: day
[ 5  6  7  8  9 12 13 14 15 16 19 20 21 23 26 27 28 29 30  2  3  4 11 17
 18 24 25  1 10 22 31]

Column: month
[ 5  6  7  8 10 11 12  1  2  3  4  9]

Column: duration
[ 261  151   76 ... 1298 1246 1556]

Column: campaign
[ 1  2  3  5  4  6  7  8  9 10 11 12 13 19 14 24 16 32 18 22 15 17 25 21
 43 51 63 41 26 28 55 50 38 23 20 29 31 37 30 46 27 58 33 35 34 36 39 44]

Column: pdays
[999 151 166  91  86 143 147  89 140 176 101 174 170 167 195 165 129 188
 196 172 118 119 104 171 117 164 132 131 123 159 186 111 115 116 173 178
 110 152  96 103 150 175 193 181 185 154 145 138 126 180 109 158 168  97
 182 127 130 194 125 105 102  26 179  28 183 155 112 120 137 124 187 190
 113 162 134 169 189   8 144 191 184 177   5  99 133  93  92  10 100 156
 198 106 153 146 128   7 121 160 107  90  27 197 136 139 122 157 149 135
  30 114  98 192 163  34  95 141  31 199  94 108  29 268 247 253 226 244
 239 245 204 231 238 258 230 254 265  71 223 246 250 266 240 205 261 259
 241 260 234 251 225 161 237 262 248 255 220 227 206 224 249 235 228 263
   2 270 232 252 207 200 269 233 256 273 272 242 264 208 214 222 271 203
 221 202 216 201 257 229 210 217  75 213  73  76 267 211 215  77 236  82
   6 209 274   1 243 212 275  80 276   9 279  12 280  88 277  85  84 219
  24  21 282  41 294  49 329 307 303 331 308 300  64 314 287 330 332 302
 323 318 333  60 326 335 313 312 305 325 327 336 309 328 322  39 316 292
 295 310 306 320 317 289  57 321 142 339 301 315 337 334 340 319  17  74
 148 341 299 344 342 324 345 346 304 281 343 338  14 347  15 291 348 349
 285 350 284  25 283 278  81   4  87  83  79  70  13 293  37  78  63  22
 296 355  66  19  35 360 357 354 351 362 358 365 298 286 364 363  47 361
 288 366 356 352 359 297 367 353 368  42 290  67 371 370 369  50  36 373
 374 372 311 375 378  59 379  40  18  43  20  69  38 385  56  55  44 391
  72 390  32  62 399 393  65 377 395 388 389 386  61 412 405 434 394 382
 459 440 397 383  68 461 462 463 422  51 457 430 442 403 454 428 392 410
 401 474 475 477 478  54 476 380 479  45  46 495  58  48 518  52 515 520
 511 536 387 218  33 544 435 436 555 433 446 558 469 616 561 553 384 592
 467 585 480 421 667 626 426 595 381 376 648 521 452 449 633 398  53 460
 670 551 414 557 687 404 651 686 425 504 578 674 416 586 411 756 450 745
 514 417 424 776 396 683 529 439 415 456 407 458 532 481 791 701 531 792
 413 445 535 784 419 455 491 431 542 470 472 717 437   3 782 728 828 524
 562 761 492 775 579 493 464 760 466 465 656 831 490 432 655 427 749 838
 769 587 778 854 779 850 771 594 842 589 603 484 489 486 409 444 680 808
 485 503 690 772 774 526 420 528 500 826 804 508 547 805 541 543 871 550
 530]

Column: previous
[  0   3   1   4   2  11  16   6   5  10  12   7  18   9  21   8  14  15
  26  37  13  25  20  27  17  23  38  29  24  51 275  22  19  30  58  28
  32  40  55  35  41]

Column: Target
[0 1]

Column: job_admin.
[0. 1.]

Column: job_blue-collar
[0. 1.]

Column: job_entrepreneur
[0. 1.]

Column: job_housemaid
[0. 1.]

Column: job_management
[1. 0.]

Column: job_retired
[0. 1.]

Column: job_self-employed
[0. 1.]

Column: job_services
[0. 1.]

Column: job_student
[0. 1.]

Column: job_technician
[0. 1.]

Column: job_unemployed
[0. 1.]

Column: job_unknown
[0. 1.]

Column: education_primary
[0. 1.]

Column: education_secondary
[0. 1.]

Column: education_tertiary
[1. 0.]

Column: education_unknown
[0. 1.]

Column: marital_divorced
[0 1]

Column: marital_married
[1 0]

Column: marital_single
[0 1]

Column: contact_cellular
[0 1]

Column: contact_telephone
[0 1]

Column: contact_unknown
[1 0]

Column: poutcome_failure
[0 1]

Column: poutcome_other
[0 1]

Column: poutcome_success
[0 1]

Column: poutcome_unknown
[1 0]

In [80]:
## DiVide the dataset into indepent and dependent features
X=data.drop('Target',axis=1)
y=data['Target']

## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

### ANN Impletation

In [82]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [83]:
(X_train.shape[1],)

(37,)

In [84]:
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid') # Output Layer
]
                   
                   
)

c:\Users\mdsal\OneDrive\Desktop\bank-marketing-response-predictor\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [85]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │         2,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,545 (17.75 KB)

 Trainable params: 4,545 (17.75 KB)

 Non-trainable params: 0 (0.00 B)

In [86]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()
loss

In [87]:
### Compile the model
model.compile(optimizer=opt, loss=loss, metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [88]:
## Setup up the tensorboard

from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [89]:
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [91]:
### Train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8956 - loss: 0.2472 - val_accuracy: 0.8957 - val_loss: 0.2410
Epoch 2/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8987 - loss: 0.2340 - val_accuracy: 0.8953 - val_loss: 0.2386
Epoch 3/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9002 - loss: 0.2283 - val_accuracy: 0.8993 - val_loss: 0.2339
Epoch 4/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9011 - loss: 0.2257 - val_accuracy: 0.8979 - val_loss: 0.2350
Epoch 5/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9001 - loss: 0.2231 - val_accuracy: 0.8979 - val_loss: 0.2310
Epoch 6/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9025 - loss: 0.2199 - val_accuracy: 0.8974 - val_loss: 0.2372
Epoch 7/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9026 - loss: 0.2184 - val_accuracy: 0.8957 - val_loss: 0.2342
Epoch 8/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9028 - loss: 0.2174 - val_accuracy: 0.8958 - val_loss: 0.2369
Epoch 9/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9035 - loss: 0.2153 - val_accuracy: 0.8998 - val_loss: 0.2315
Epoch 10/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9030 - loss: 0.2144 - val_accuracy: 0.8976 - val_loss: 0.2307
Epoch 11/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9044 - loss: 0.2119 - val_accuracy: 0.8957 - val_loss: 0.2367
Epoch 12/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9056 - loss: 0.2097 - val_accuracy: 0.8970 - val_loss: 0.2389
Epoch 13/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9051 - loss: 0.2082 - val_accuracy: 0.8944 - val_loss: 0.2325
Epoch 14/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9033 - loss: 0.2070 - val_accuracy: 0.8944 - val_loss: 0.2379
Epoch 15/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9055 - loss: 0.2063 - val_accuracy: 0.8967 - val_loss: 0.2428
Epoch 16/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9054 - loss: 0.2050 - val_accuracy: 0.8982 - val_loss: 0.2303
Epoch 17/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9041 - loss: 0.2044 - val_accuracy: 0.8988 - val_loss: 0.2317
Epoch 18/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9057 - loss: 0.2061 - val_accuracy: 0.8860 - val_loss: 0.2431
Epoch 19/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9068 - loss: 0.2020 - val_accuracy: 0.8990 - val_loss: 0.2361
Epoch 20/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9054 - loss: 0.2009 - val_accuracy: 0.8952 - val_loss: 0.2381
Epoch 21/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9070 - loss: 0.1988 - val_accuracy: 0.8969 - val_loss: 0.2629
Epoch 22/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9057 - loss: 0.1993 - val_accuracy: 0.8975 - val_loss: 0.2451
Epoch 23/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9077 - loss: 0.1974 - val_accuracy: 0.8931 - val_loss: 0.2455
Epoch 24/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9091 - loss: 0.1962 - val_accuracy: 0.8933 - val_loss: 0.2467
Epoch 25/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9093 - loss: 0.1948 - val_accuracy: 0.8949 - val_loss: 0.2564
Epoch 26/100
1131/1131 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9066 - loss: 0.1961 - val_accuracy: 0.8963 - val_loss: 0.2489

In [92]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [93]:
%load_ext tensorboard

In [96]:
%tensorboard --logdir logs/fit20261024-180038

Reusing TensorBoard on port 6006 (pid 5592), started 0:00:25 ago. (Use '!kill 5592' to kill it.)